name: MultiPlatformUnitTest

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_test:
    name: Unit test with Tor

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        go:
          - "1.25"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Install Tor (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y tor

      - name: Install Tor (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install tor

      - name: Install Tor (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install tor -y
          # Add Tor to PATH
          echo "C:\ProgramData\chocolatey\lib\tor\tools\Tor" >> $env:GITHUB_PATH

      - name: Run integration tests with coverage
        run: make integration-test
        env:
          TORNAGO_INTEGRATION: "1"

